'use strict';
const fs=require('fs'),path=require('path');
const addon=path.join(__dirname,'addon','WoWAI');
// Embed in the existing loaded file as well, so /reload works with a cached TOC.
// Research.lua's guard makes the standalone manifest entry harmless.
const core=fs.readFileSync(path.join(addon,'WoWAI.core.lua'),'utf8');
const research=fs.readFileSync(path.join(addon,'Research.lua'),'utf8');
const settings=fs.readFileSync(path.join(addon,'Settings.lua'),'utf8');
const embed=text=>text.split('\n').map(line=>line.trim()?'  '+line:'').join('\n');
fs.writeFileSync(path.join(addon,'WoWAI.lua'),core+'\n\n-- Goblin Eye research UI (generated by build-addon.js)\ndo\n'+embed(research)+'\nend\n\n-- Per-chat model/settings UI\ndo\n'+embed(settings)+'\nend\n');
console.log('Built reload-compatible WoWAI.lua.');
